<?php

namespace AppBundle\Repository;

/**
 * BeaconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeaconRepository extends \Doctrine\ORM\EntityRepository
{
}
