<?php

namespace AppBundle\Repository;

/**
 * PoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoiRepository extends \Doctrine\ORM\EntityRepository
{
	public function findCount()
	{
		return $this->createQueryBuilder('e')
			->select('count(e.id)')
			->getQuery()
			->getSingleScalarResult();
	}
}
